# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(default='Datos de la Actividad:', max_length=255)),
                ('date', models.DateTimeField()),
                ('horas', models.IntegerField()),
                ('carne', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AsigActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaPrincipal.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carne', models.IntegerField()),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=64)),
                ('contrasena', models.CharField(max_length=64)),
                ('horasPendientes', models.IntegerField()),
                ('horasRealizadas', models.IntegerField()),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='asigactividad',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaPrincipal.Usuario'),
        ),
    ]
